stages:
- build
- docker
- publish

#--------------------------
# Build templates
#--------------------------

.build-template: &build-template_definition
  stage: build
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
    - tree ${CI_JOB_NAME}
  variables:
    BRANCH: ${CI_COMMIT_REF_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

#--------------------------
# Build jobs
#--------------------------

cc7:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  <<: *build-template_definition

#--------------------------
# Docker build jobs
#--------------------------

build:
  stage: docker
  only:
    - develop
  script:
    - ""
  variables:
    TO: gitlab-registry.cern.ch/fts/fts-monitoring:latest
    DOCKER_FILE: packaging/docker/Dockerfile
  tags:
    - docker-image-build

tag:
  stage: docker
  only:
    - tags
  script:
    - ""
  variables:
    TO: gitlab-registry.cern.ch/fts/fts-monitoring:$CI_BUILD_REF_NAME
    DOCKER_FILE: packaging/docker/Dockerfile-release
  tags:
    - docker-image-build

#--------------------------
# Publish templates
#--------------------------

.publish-template: &publish-template_definition
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  dependencies:
    - cc7
  script:
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$repo_passwd" | kinit "$repo_user"
    - eosfusebind
    - packaging/fts-repo-manager.py --action add --base /eos/workspace/f/fts/repo/www/repos/ --ref ${CI_COMMIT_REF_NAME} --packages cc7/RPMS/*/*.rpm cc7/SRPMS/*
    - sleep 60
  tags:
    - docker-privileged
  retry: 2

#--------------------------
# Publish jobs
#--------------------------

rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_TAG!= null'

testing-rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_COMMIT_REF_NAME != "develop" && $CI_COMMIT_TAG == null'
      when: manual

sync-production:
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/cc7:latest
  script:
    - yum install -y python sssd-client sudo createrepo
    - automount
    - cat "$repo_passwd" | kinit "$repo_user"
    - eosfusebind
    - packaging/syncrepo --base-origin /eos/workspace/f/fts/repo/www/repos/rc --base-dest /eos/workspace/f/fts/repo/www/repos/ '*.rpm'
    - sleep 60
  tags:
    - docker-privileged
  retry: 2
  rules:
    - if: $CI_COMMIT_TAG != null
      when: manual
