image: docker:latest

stages:
- build
- tag

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.cern.ch/fts/fts-monitoring:latest
  CONTAINER_RELEASE_IMAGE: gitlab-registry.cern.ch/fts/fts-monitoring:$CI_BUILD_REF_NAME

before_script:
    - docker info
    - docker login -p "${REGISTRY_PASSWD}" -u "${REGISTRY_USER}" gitlab-registry.cern.ch

after_script:
    - docker logout gitlab-registry.cern.ch

build:
    stage: build
    only:
      - develop
    script:
      - docker build --pull -t $CONTAINER_TEST_IMAGE packaging/docker
      - docker push $CONTAINER_TEST_IMAGE
    tags:
      - docker
tag:
    stage: tag
    only:
        - tags
    script:
        - docker build  -t $CONTAINER_RELEASE_IMAGE --build-arg ftsrepo=http://fts-repo.web.cern.ch/fts-repo/fts3-prod-el7.repo   packaging/docker  
    tags:
       - docker
