stages:
- build
- tag

build:
    stage: build
    only:
      - develop
    script:
      - ""
    variables:
      TO: gitlab-registry.cern.ch/fts/fts-monitoring:latest
      DOCKER_FILE:  packaging/docker/Dockerfile
    tags:
      - docker-image-build
tag:
    stage: tag
    only:
        - tags
    script:
      - ""
    variables:
      TO: gitlab-registry.cern.ch/fts/fts-monitoring:$CI_BUILD_REF_NAME
      DOCKER_FILE:  packaging/docker/Dockerfile-release
    tags:
        - docker-image-build

