stages:
- build
- docker
- publish

#--------------------------
# Build templates
#--------------------------

.build-template: &build-template_definition
  stage: build
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
    - tree ${CI_JOB_NAME}
  variables:
    BRANCH: ${CI_COMMIT_REF_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

#--------------------------
# Build jobs
#--------------------------

alma9:
  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  <<: *build-template_definition

#--------------------------
# Docker build templates
#--------------------------

.kaniko_build: &kaniko_build-template
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - if [[ -z "$CI_COMMIT_TAG" ]]; then CACHE="true" ; else CACHE="false"; fi
    - DESTINATION="gitlab-registry.cern.ch/fts/fts-monitoring:${REGISTRY}"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --dockerfile ci/docker/Dockerfile-ci --context "${CI_PROJECT_DIR}" --cache=${CACHE} --destination ${DESTINATION}
  retry: 1

#--------------------------
# Docker build jobs
#--------------------------

docker_latest:
  <<: *kaniko_build-template
  variables:
    DESTINATION: gitlab-registry.cern.ch/fts/fts-monitoring:latest
  needs:
    - job: alma9
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop"

docker_tag:
  <<: *kaniko_build-template
  variables:
    DESTINATION: gitlab-registry.cern.ch/fts/fts-monitoring:${CI_COMMIT_TAG}
  needs:
    - job: alma9
  rules:
    - if: $CI_COMMIT_TAG != null

#--------------------------
# Publish templates
#--------------------------

.publish-template: &publish-template_definition
  stage: publish
  image: gitlab-registry.cern.ch/eos/gitlab-eos/alma9:latest
  dependencies:
    - alma9
  script:
    - automount
    - cat "$repo_passwd" | kinit "$repo_user"
    - packaging/fts-repo-manager.py --action add --base /eos/workspace/f/fts/repo/www/repos/ --ref ${CI_COMMIT_REF_NAME} --arch-dir x86_64 --packages alma9/RPMS/*/*.rpm alma9/SRPMS/*
  tags:
    - docker-privileged-xl
  retry: 2

#--------------------------
# Publish jobs
#--------------------------

rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_TAG!= null'

testing-rpms:
  <<: *publish-template_definition
  rules:
    - if: '$CI_COMMIT_REF_NAME != "develop" && $CI_COMMIT_TAG == null'
      when: manual
